//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTongKet
    {
        public int Id { get; set; }
        public int Id_CuaHang { get; set; }
        public string Ngay { get; set; }
        public decimal SoTienDauNgay { get; set; }
        public decimal CamDo_Thu { get; set; }
        public decimal CamDo_Chi { get; set; }
        public decimal VayLai_Thu { get; set; }
        public decimal VayLai_Chi { get; set; }
        public decimal BatHo_Thu { get; set; }
        public decimal BatHo_Chi { get; set; }
        public decimal HoatDong_Thu { get; set; }
        public decimal HoatDong_Chi { get; set; }
        public decimal NguonVon_Thu { get; set; }
        public decimal NguonVon_Chi { get; set; }
    }
}
