//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoHangNgay
    {
        public int Id { get; set; }
        public int Id_CuaHang { get; set; }
        public System.DateTime Ngay { get; set; }
        public decimal SoTienVonDauNgay { get; set; }
        public decimal SoTienVonConLai { get; set; }
        public decimal TongThu { get; set; }
        public decimal TongChi { get; set; }
        public decimal TongThuHopDongBatHo { get; set; }
        public decimal TongThuHopDongCamDo { get; set; }
        public decimal TongThuHopDongChoVay { get; set; }
        public decimal TongThuHopDongChoVayDNGD { get; set; }
        public decimal TongChiHopDongBatHo { get; set; }
        public decimal TongChiHopDongCamDo { get; set; }
        public decimal TongChiHopDongChoVay { get; set; }
        public decimal TongChiHopDongChoVayDNGD { get; set; }
        public decimal TongThuKhac { get; set; }
        public decimal TongChiKhac { get; set; }
    }
}
