//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        public int MaCuaHang { get; set; }
        public string TenCuaHang { get; set; }
        public string DiaChi { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<decimal> VonDauTu { get; set; }
        public Nullable<decimal> QuyTienMat { get; set; }
        public string NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int TinhTrang { get; set; }
        public string QuanLyCuaHang { get; set; }
    }
}
