//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_BatHo
    {
        public int Id { get; set; }
        public string HD_BatHo_Id { get; set; }
        public string KhachHang_CMND { get; set; }
        public decimal BatHo { get; set; }
        public decimal TienDuaChoKhach { get; set; }
        public int BocTrongVong { get; set; }
        public int SoNgayDongTien { get; set; }
        public System.DateTime NgayBoc { get; set; }
        public bool ThuHoTruoc { get; set; }
        public string GhiChu { get; set; }
        public int CuaHang_Id { get; set; }
        public string NhanVien_Id { get; set; }
        public System.DateTime NgayTao { get; set; }
        public decimal SoTienKhachDaDong { get; set; }
        public Nullable<System.DateTime> NgayCuoiCungDongTien { get; set; }
        public string TinhTrang { get; set; }
    }
}
