//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_CamDo
    {
        public int Id { get; set; }
        public string HD_CamDo_Id { get; set; }
        public string KhachHang_HoTen { get; set; }
        public string KhachHang_CMND { get; set; }
        public string MaTaiSan { get; set; }
        public string TaiSan { get; set; }
        public decimal SoTienCam { get; set; }
        public System.DateTime NgayCam { get; set; }
        public int HinhThucLai { get; set; }
        public int Lai { get; set; }
        public int KyLai { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayThanhLyHopDong { get; set; }
        public int CuaHang_Id { get; set; }
        public string NhanVien_Id { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCuoiCungDongTienLai { get; set; }
    }
}
