//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_VayDuNoGiamDan
    {
        public int Id { get; set; }
        public string HD_Id { get; set; }
        public string KhachHang_CMND { get; set; }
        public decimal SoTienVay { get; set; }
        public double HoaHong { get; set; }
        public double LaiSuat { get; set; }
        public int ThoiHanVay { get; set; }
        public System.DateTime NgayVay { get; set; }
        public string GhiChu { get; set; }
        public int CuaHang_Id { get; set; }
        public string NhanVien_Id { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCuoiCungDongTien { get; set; }
        public string TinhTrang { get; set; }
        public System.DateTime NgayBatDauDongLai { get; set; }
        public Nullable<System.DateTime> NgayHenGio { get; set; }
        public string GhiChuHenGio { get; set; }
        public int TrangThaiHenGio { get; set; }
        public string UrlHinh1 { get; set; }
        public string UrlHinh2 { get; set; }
        public string UrlHinh3 { get; set; }
        public decimal TienLaiDaDong { get; set; }
    }
}
