//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int ID_KhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string CMND { get; set; }
        public string HinhDaiDien { get; set; }
        public string SoDienThoai1 { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai2 { get; set; }
        public string LoaiNha { get; set; }
        public string SoHuuNha { get; set; }
        public Nullable<System.DateTime> NgayCapCMND { get; set; }
        public string NoiCapCMND { get; set; }
        public string NguyenQuan { get; set; }
        public string TinhTrangHonNhan { get; set; }
        public string KhuVuc { get; set; }
        public string BienSoXe { get; set; }
        public string LoaiXe { get; set; }
        public string SoHuuXe { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChiCongTy { get; set; }
        public string ChucVu { get; set; }
        public string ThoiGianLamViecBaoLau { get; set; }
        public string TenNguoiBaoLanh { get; set; }
        public string DiaChiNguoiBaoLanh { get; set; }
        public string SoDienThoaiNguoiBaoLanh { get; set; }
        public string DiaChiLamViecNguoiBaoLanh { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
        public Nullable<int> NgayLanhLuong { get; set; }
        public Nullable<decimal> CotLuongTienMat { get; set; }
        public string TenNganHang { get; set; }
        public string ChuTaiKhoan { get; set; }
        public string SoTaiKhoan { get; set; }
        public string SoThe { get; set; }
        public string MaHoaThe { get; set; }
        public string HinhCMNDMatTruoc { get; set; }
        public string HinhCMNDMatSau { get; set; }
    }
}
