//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuThaoTac
    {
        public int Id { get; set; }
        public int Id_CuaHang { get; set; }
        public string Id_NhanVienThaoTac { get; set; }
        public string Id_HopDong { get; set; }
        public decimal SoTien { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayThaoTac { get; set; }
        public int ThuTien { get; set; }
        public decimal TongCongTon { get; set; }
        public string TenKhachHang { get; set; }
    }
}
