//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThayDoiSoTienHopDong
    {
        public int Id { get; set; }
        public string HopDong_Id { get; set; }
        public decimal SoTien { get; set; }
        public int Loai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayThucHien { get; set; }
    }
}
