//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDongLai
    {
        public int Id { get; set; }
        public string HopDong_Id { get; set; }
        public decimal TienLai { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int DaDong { get; set; }
        public Nullable<decimal> TienKhac { get; set; }
        public int SoNgay { get; set; }
        public string NhanVienThuTien { get; set; }
        public Nullable<System.DateTime> NgayDongLai { get; set; }
        public string GhiChu { get; set; }
        public decimal SoTienDaDong { get; set; }
    }
}
