//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIT.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinThuChi
    {
        public int Id { get; set; }
        public int Id_CuaHang { get; set; }
        public string Id_NhanVien { get; set; }
        public string KhachHang { get; set; }
        public decimal SoTien { get; set; }
        public string LoaiPhieu { get; set; }
        public string GhiChu { get; set; }
        public int PhieuThu { get; set; }
        public System.DateTime NgayTao { get; set; }
    }
}
